# Generated by Django 5.1.5 on 2025-01-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=10, verbose_name='Статус'),
        ),
    ]
